# Generated by Django 6.0.8 on 2026-09-01 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0004_alter_salesorder_order_number'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=50, unique=True, verbose_name='Sevkiyat No')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Miktar')),
                ('status', models.CharField(choices=[('pending', 'Hazırlanıyor'), ('shipped', 'Kargoya Verildi'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Kargoya Veriliş Tarihi')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='distribution.salesorder', verbose_name='Satış Siparişi')),
                ('sales_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='distribution.salesorderline', verbose_name='Sipariş Kalemi')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='inventory.warehouse', verbose_name='Depo')),
            ],
            options={
                'verbose_name': 'Sevkiyat',
                'verbose_name_plural': 'Sevkiyatlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
