# Generated by Django 6.0.8 on 2026-08-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_customer_user_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Sipariş Numarası'),
        ),
    ]
