# Generated by Django 6.0.8 on 2026-09-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_alter_salesorder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='emailed_at',
            field=models.DateTimeField(blank=True, help_text='Fatura müşteriye e-posta ile gönderildiğinde doldurulur.', null=True, verbose_name='Fatura E-posta Gönderim Tarihi'),
        ),
    ]
