# Generated by Django 6.1 on 2026-08-25 09:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Hat Kodu')),
                ('name', models.CharField(max_length=150, verbose_name='Hat Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('capacity_per_day', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Günlük Kapasite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Üretim Hattı',
                'verbose_name_plural': 'Üretim Hatları',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Reçete Versiyonu')),
                ('name', models.CharField(max_length=150, verbose_name='Reçete Adı')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('active', 'Aktif'), ('inactive', 'Pasif')], default='draft', max_length=20, verbose_name='Durum')),
                ('output_quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Üretim Çıktı Miktarı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Geçerlilik Başlangıcı')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Geçerlilik Bitişi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_of_material', to='inventory.product', verbose_name='Üretilecek Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Reçetesi',
                'verbose_name_plural': 'Ürün Reçeteleri',
                'ordering': ['product', '-version'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Miktar')),
                ('scrap_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fire Oranı (%)')),
                ('operation_sequence', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kullanıldığı Operasyon Sırası')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('bill_of_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.billofmaterial', verbose_name='Ürün Reçetesi')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='inventory.product', verbose_name='Bileşen')),
            ],
            options={
                'verbose_name': 'Reçete Kalemi',
                'verbose_name_plural': 'Reçete Kalemleri',
                'ordering': ['bill_of_material', 'operation_sequence', 'component'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='Üretim Emri No')),
                ('planned_quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Planlanan Miktar')),
                ('produced_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Üretilen Miktar')),
                ('scrapped_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fire Miktarı')),
                ('status', models.CharField(choices=[('planned', 'Planlandı'), ('released', 'Serbest Bırakıldı / Başlatılabilir'), ('in_progress', 'Üretimde'), ('quality_check', 'Kalite Kontrolde'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='planned', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='medium', max_length=10, verbose_name='Öncelik')),
                ('planned_start_date', models.DateTimeField(verbose_name='Planlanan Başlangıç')),
                ('planned_end_date', models.DateTimeField(verbose_name='Planlanan Bitiş')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Gerçekleşen Başlangıç')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Gerçekleşen Bitiş')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_of_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='production.billofmaterial', verbose_name='Kullanılacak Reçete')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_production_orders', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='inventory.product', verbose_name='Üretilecek Ürün')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='production.productionline', verbose_name='Üretim Hattı')),
            ],
            options={
                'verbose_name': 'Üretim Emri',
                'verbose_name_plural': 'Üretim Emirleri',
                'ordering': ['-planned_start_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Gereken Miktar')),
                ('consumed_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Tüketilen Miktar')),
                ('is_fully_consumed', models.BooleanField(default=False, verbose_name='Tamamı Tüketildi mi?')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_requirements', to='inventory.product', verbose_name='Hammadde / Yarı Mamul')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_components', to='production.productionorder', verbose_name='Üretim Emri')),
            ],
            options={
                'verbose_name': 'Üretim Emri Hammaddesi',
                'verbose_name_plural': 'Üretim Emri Hammaddeleri',
            },
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Versiyon')),
                ('name', models.CharField(max_length=150, verbose_name='Rota Adı')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('active', 'Aktif'), ('inactive', 'Pasif')], default='draft', max_length=20, verbose_name='Durum')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Geçerlilik Başlangıcı')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Geçerlilik Bitişi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routings', to='inventory.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Üretim Rotası',
                'verbose_name_plural': 'Üretim Rotaları',
                'ordering': ['product', '-version'],
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='routing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='production.routing', verbose_name='Kullanılacak Rota'),
        ),
        migrations.CreateModel(
            name='RoutingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sıra')),
                ('name', models.CharField(max_length=150, verbose_name='Operasyon Adı')),
                ('setup_time_minutes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Hazırlık Süresi (Dakika)')),
                ('cycle_time_minutes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Çevrim Süresi (Dakika)')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='production.routing', verbose_name='Üretim Rotası')),
            ],
            options={
                'verbose_name': 'Rota Operasyonu',
                'verbose_name_plural': 'Rota Operasyonları',
                'ordering': ['routing', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('in_progress', 'İşlemde'), ('completed', 'Tamamlandı'), ('paused', 'Duraklatıldı')], default='pending', max_length=20, verbose_name='Durum')),
                ('completed_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, verbose_name='Tamamlanan Miktar')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Başlama Zamanı')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('operator_notes', models.TextField(blank=True, verbose_name='Operatör Notları')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_operations', to='production.productionorder', verbose_name='Üretim Emri')),
                ('routing_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_operations', to='production.routingoperation', verbose_name='Rota Operasyonu')),
            ],
            options={
                'verbose_name': 'Üretim Emri Operasyonu',
                'verbose_name_plural': 'Üretim Emri Operasyonları',
                'ordering': ['production_order', 'routing_operation__sequence'],
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='İş Merkezi Kodu')),
                ('name', models.CharField(max_length=150, verbose_name='İş Merkezi Adı')),
                ('machine_name', models.CharField(blank=True, max_length=150, verbose_name='Makine Adı')),
                ('capacity_per_hour', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Saatlik Kapasite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_centers', to='production.productionline', verbose_name='Üretim Hattı')),
            ],
            options={
                'verbose_name': 'İş Merkezi',
                'verbose_name_plural': 'İş Merkezleri',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='routingoperation',
            name='work_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_operations', to='production.workcenter', verbose_name='İş Merkezi'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterial',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='unique_product_bom_version'),
        ),
        migrations.AddConstraint(
            model_name='bomitem',
            constraint=models.UniqueConstraint(fields=('bill_of_material', 'component'), name='unique_bom_component'),
        ),
        migrations.AddConstraint(
            model_name='routing',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='unique_product_routing_version'),
        ),
        migrations.AddConstraint(
            model_name='routingoperation',
            constraint=models.UniqueConstraint(fields=('routing', 'sequence'), name='unique_routing_operation_sequence'),
        ),
    ]
