# Generated by Django 6.1 on 2026-08-25 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='finished_goods_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders_finished', to='inventory.warehouse', verbose_name='Mamul Deposu'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='raw_materials_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders_raw', to='inventory.warehouse', verbose_name='Hammadde Deposu'),
        ),
    ]
