# Generated by Django 6.1 on 2026-08-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionorder_finished_goods_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='reference_order_number',
            field=models.CharField(blank=True, help_text='Bu üretim emrinin bağlı olduğu satış siparişi numarası.', max_length=50, null=True, verbose_name='Referans Sipariş No'),
        ),
    ]
