# Generated by Django 5.2.12 on 2026-09-01 13:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_lot_stockmovement_lot'),
        ('production', '0003_productionorder_reference_order_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_material_cost', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Hammadde Maliyeti')),
                ('labor_cost', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='İşçilik Maliyeti')),
                ('machine_cost', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Makine / Operasyon Maliyeti')),
                ('overhead_cost', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Genel Üretim Gideri')),
                ('scrap_cost', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fire Maliyeti')),
                ('total_cost', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Toplam Maliyet')),
                ('produced_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Sağlam Üretim Miktarı')),
                ('scrap_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fire Miktarı')),
                ('unit_cost', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Birim Maliyet')),
                ('calculation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hesaplama Tarihi')),
                ('creation_source', models.CharField(choices=[('manual', 'Manuel'), ('auto', 'Otomatik')], default='manual', max_length=40, verbose_name='Hesaplama Kaynağı')),
                ('calculation_version', models.PositiveIntegerField(default=1, verbose_name='Hesaplama Versiyonu')),
                ('calculation_note', models.TextField(blank=True, verbose_name='Hesaplama Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_costs', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan / Güncelleyen')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_costs', to='inventory.lot', verbose_name='Lot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_costs', to='inventory.product', verbose_name='Ürün')),
                ('production_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_cost', to='production.productionorder', verbose_name='Üretim Emri')),
            ],
            options={
                'verbose_name': 'Üretim Maliyeti',
                'verbose_name_plural': 'Üretim Maliyetleri',
                'ordering': ['-calculation_date', '-pk'],
            },
        ),
    ]
