# Generated by Django 6.0.8 on 2026-09-01 11:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=60, unique=True, verbose_name='Lot Numarası')),
                ('reference_type', models.CharField(blank=True, help_text='Lotun oluştuğu kayıt türü. Örneğin: ProductionOrder, PurchaseOrder.', max_length=50, verbose_name='Referans Türü')),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Referans ID')),
                ('manufactured_date', models.DateField(blank=True, null=True, verbose_name='Üretim Tarihi')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Son Kullanma Tarihi')),
                ('initial_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Başlangıç Miktarı')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('quarantined', 'Karantinada'), ('consumed', 'Tükendi'), ('expired', 'Süresi Doldu')], default='active', max_length=20, verbose_name='Durum')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='Bu hareketin ilişkili olduğu lot (varsa).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.lot', verbose_name='Lot'),
        ),
    ]
