# Generated by Django 5.2.12 on 2026-09-01

from django.db import migrations, models


def backfill_identifiers(apps, schema_editor):
    Product = apps.get_model("inventory", "Product")
    Lot = apps.get_model("inventory", "Lot")
    for product in Product.objects.filter(barcode__isnull=True).iterator():
        product.barcode = f"PRD-{product.pk:012d}"
        product.qr_code = f"ERP|PRODUCT|{product.pk}|{product.code}"
        product.save(update_fields=["barcode", "qr_code"])
    for lot in Lot.objects.filter(barcode__isnull=True).select_related("product").iterator():
        lot.barcode = f"LOT-{lot.pk:012d}"
        lot.qr_code = f"ERP|LOT|{lot.pk}|{lot.product.code}|{lot.lot_number}"
        lot.save(update_fields=["barcode", "qr_code"])


class Migration(migrations.Migration):
    dependencies = [("inventory", "0002_lot_stockmovement_lot")]

    operations = [
        migrations.AddField(
            model_name="lot", name="barcode",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="lot", name="qr_code",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product", name="barcode",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="product", name="qr_code",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(backfill_identifiers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="lot", name="barcode",
            field=models.CharField(blank=True, db_index=True, help_text="Lot için tekil barkod değeri. Mevcut değer değişmez.", max_length=64, unique=True, verbose_name="Lot Barkodu"),
        ),
        migrations.AlterField(
            model_name="lot", name="qr_code",
            field=models.CharField(blank=True, db_index=True, help_text="Lot için tekil QR kod metni. Hassas bilgi içermez.", max_length=255, unique=True, verbose_name="Lot QR Kodu"),
        ),
        migrations.AlterField(
            model_name="product", name="barcode",
            field=models.CharField(blank=True, db_index=True, help_text="Ürün için tekil barkod değeri. Mevcut değer değişmez; yeniden oluşturulmaz.", max_length=64, unique=True, verbose_name="Barkod"),
        ),
        migrations.AlterField(
            model_name="product", name="qr_code",
            field=models.CharField(blank=True, db_index=True, help_text="Ürün için tekil QR kod metni. Hassas bilgi içermez.", max_length=255, unique=True, verbose_name="QR Kodu"),
        ),
        migrations.AddField(
            model_name="stockmovement", name="scan_reference",
            field=models.CharField(blank=True, db_index=True, help_text="Aynı barkod/QR okutması tekrar stok hareketi oluşturmasın diye tekil referans.", max_length=128, null=True, unique=True, verbose_name="Tarama Referansı"),
        ),
    ]
