# Generated by Django 6.1 on 2026-08-26 06:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0002_productionorder_finished_goods_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kontrol Tarihi')),
                ('checked_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Kontrol Edilen Miktar')),
                ('accepted_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Kabul Edilen Miktar')),
                ('rejected_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Reddedilen Miktar')),
                ('scrapped_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fire Miktarı')),
                ('result', models.CharField(choices=[('pass', 'Kabul (Geçti)'), ('partial', 'Kısmi Kabul'), ('fail', 'Red')], default='pass', max_length=20, verbose_name='Sonuç')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Red / Fire Nedeni')),
                ('notes', models.TextField(blank=True, verbose_name='Kontrol Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to=settings.AUTH_USER_MODEL, verbose_name='Kontrol Eden')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='production.productionorder', verbose_name='Üretim Emri')),
            ],
            options={
                'verbose_name': 'Kalite Kontrol Kaydı',
                'verbose_name_plural': 'Kalite Kontrol Kayıtları',
                'ordering': ['-check_date'],
            },
        ),
    ]
