# Generated by Django 6.1 on 2026-08-25 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Renk Kodu')),
                ('name', models.CharField(max_length=50, verbose_name='Renk Adı')),
                ('hex_code', models.CharField(blank=True, help_text='Örn: #000000', max_length=7, verbose_name='HEX Kodu')),
            ],
            options={
                'verbose_name': 'Renk',
                'verbose_name_plural': 'Renkler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShoeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Model Kodu')),
                ('name', models.CharField(max_length=150, verbose_name='Model Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('target_gender', models.CharField(choices=[('men', 'Erkek'), ('women', 'Kadın'), ('unisex', 'Unisex'), ('kids', 'Çocuk')], default='unisex', max_length=20, verbose_name='Hedef Kitle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Ayakkabı Modeli',
                'verbose_name_plural': 'Ayakkabı Modelleri',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_value', models.CharField(max_length=10, unique=True, verbose_name='Numara')),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Numara',
                'verbose_name_plural': 'Numaralar',
                'ordering': ['size_value'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU / Barkod')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.color', verbose_name='Renk')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='variant_details', to='inventory.product', verbose_name='İlişkili Envanter Ürünü')),
                ('shoe_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.shoemodel', verbose_name='Ayakkabı Modeli')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.size', verbose_name='Numara')),
            ],
            options={
                'verbose_name': 'Ürün Varyantı',
                'verbose_name_plural': 'Ürün Varyantları',
                'ordering': ['shoe_model', 'color', 'size'],
                'constraints': [models.UniqueConstraint(fields=('shoe_model', 'color', 'size'), name='unique_shoe_color_size_combination')],
            },
        ),
    ]
