# Generated by Django 5.2.12 on 2026-09-03 14:43

import ai.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('file', models.FileField(max_length=500, upload_to=ai.models.document_upload_path, verbose_name='Dosya')),
                ('original_filename', models.CharField(editable=False, max_length=255, verbose_name='Orijinal Dosya Adı')),
                ('mime_type', models.CharField(editable=False, max_length=127, verbose_name='MIME Türü')),
                ('file_size', models.PositiveBigIntegerField(editable=False, verbose_name='Dosya Boyutu')),
                ('checksum_sha256', models.CharField(db_index=True, editable=False, max_length=64, verbose_name='SHA-256')),
                ('status', models.CharField(choices=[('uploaded', 'Yüklendi'), ('processing', 'İşleniyor'), ('ready', 'Hazır'), ('failed', 'Başarısız')], default='uploaded', editable=False, max_length=20, verbose_name='Durum')),
                ('processing_error', models.TextField(blank=True, editable=False, verbose_name='İşleme Hatası')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_documents', to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'AI Dokümanı',
                'verbose_name_plural': 'AI Dokümanları',
                'ordering': ['-created_at'],
            },
        ),
    ]
