# Generated by Django 6.1 on 2026-08-25 07:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='Sipariş Numarası')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Beklenen Teslim Tarihi')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('sent', 'Gönderildi'), ('confirmed', 'Onaylandı'), ('partially_received', 'Kısmen Teslim Alındı'), ('received', 'Tamamı Teslim Alındı'), ('cancelled', 'İptal Edildi')], default='draft', max_length=25, verbose_name='Durum')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Toplam Tutar')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Satın Alma Siparişi',
                'verbose_name_plural': 'Satın Alma Siparişleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Tedarikçi Kodu')),
                ('name', models.CharField(max_length=200, verbose_name='Firma Adı')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Vergi Numarası')),
                ('contact_person', models.CharField(blank=True, max_length=150, verbose_name='Yetkili Kişi')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('payment_terms', models.CharField(blank=True, max_length=100, verbose_name='Ödeme Koşulları')),
                ('delivery_lead_time_days', models.PositiveIntegerField(default=0, verbose_name='Standart Teslim Süresi (Gün)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tedarikçi',
                'verbose_name_plural': 'Tedarikçiler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=30, unique=True, verbose_name='Mal Kabul Numarası')),
                ('received_date', models.DateField(auto_now_add=True, verbose_name='Teslim Tarihi')),
                ('delivered_by', models.CharField(blank=True, max_length=150, verbose_name='Teslim Eden')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('received', 'Teslim Alındı'), ('inspection', 'Kalite Kontrol Bekliyor'), ('accepted', 'Kabul Edildi'), ('partially_accepted', 'Kısmen Kabul Edildi'), ('rejected', 'Reddedildi')], default='draft', max_length=25, verbose_name='Durum')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='procurement.purchaseorder', verbose_name='Satın Alma Siparişi')),
            ],
            options={
                'verbose_name': 'Mal Kabul',
                'verbose_name_plural': 'Mal Kabuller',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Sipariş Miktarı')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Birim Fiyat')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='KDV Oranı (%)')),
                ('received_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Teslim Alınan Miktar')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='inventory.product', verbose_name='Ürün')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder', verbose_name='Satın Alma Siparişi')),
            ],
            options={
                'verbose_name': 'Satın Alma Sipariş Kalemi',
                'verbose_name_plural': 'Satın Alma Sipariş Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Gelen Miktar')),
                ('accepted_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Kabul Edilen Miktar')),
                ('rejected_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Reddedilen Miktar')),
                ('lot_number', models.CharField(blank=True, max_length=100, verbose_name='Lot Numarası')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.goodsreceipt', verbose_name='Mal Kabul')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_items', to='inventory.product', verbose_name='Ürün')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_items', to='inventory.warehouse', verbose_name='Hedef Depo')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_items', to='procurement.purchaseorderitem', verbose_name='Sipariş Kalemi')),
            ],
            options={
                'verbose_name': 'Mal Kabul Kalemi',
                'verbose_name_plural': 'Mal Kabul Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=30, unique=True, verbose_name='Talep Numarası')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='Talep Tarihi')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='Gerekli Tarih')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Gönderildi'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('ordered', 'Siparişe Dönüştü'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden')),
            ],
            options={
                'verbose_name': 'Satın Alma Talebi',
                'verbose_name_plural': 'Satın Alma Talepleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.purchaserequest', verbose_name='Bağlı Satın Alma Talebi'),
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Miktar')),
                ('reason', models.TextField(blank=True, verbose_name='Talep Gerekçesi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_items', to='inventory.product', verbose_name='Ürün')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaserequest', verbose_name='Satın Alma Talebi')),
            ],
            options={
                'verbose_name': 'Satın Alma Talep Kalemi',
                'verbose_name_plural': 'Satın Alma Talep Kalemleri',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.supplier', verbose_name='Tedarikçi'),
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_product_code', models.CharField(blank=True, max_length=100, verbose_name='Tedarikçi Ürün Kodu')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Birim Fiyat')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('minimum_order_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Minimum Sipariş Miktarı')),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='Teslim Süresi (Gün)')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='Tercih Edilen Tedarikçi mi?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_products', to='inventory.product', verbose_name='Ürün')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_products', to='procurement.supplier', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Tedarikçi Ürünü',
                'verbose_name_plural': 'Tedarikçi Ürünleri',
                'ordering': ['supplier', 'product'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'product'), name='unique_purchase_order_product'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(fields=('supplier', 'product'), name='unique_supplier_product'),
        ),
    ]
