# Generated by Django 5.2.12 on 2026-08-27 10:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_preserve_legacy_procurement_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='note',
            field=models.TextField(blank=True, verbose_name='Sipariş Notu'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Birim Fiyat'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='purpose',
            field=models.TextField(blank=True, verbose_name='Talep Açıklaması'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='requested_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Talep Miktarı'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Firma Unvanı'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
